language: java
jdk: openjdk11

before_script:
  - wget -q https://storage.googleapis.com/ig-build/org.hl7.fhir.validator.jar -O validator.jar

script:
  - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8
  - java -jar validator.jar -version 4.0.0 beispiele -ig datentypen-profile -ig extensions -ig ressourcen-profile -ig terminologie -recurse
